name: "Action.ts"
description: "GitHub Actions starter for TypeScript with automated releases"
author: "Koj <https://github.com/koj.co>"
inputs:
  milliseconds:
    required: true
    description: "Number of milliseconds to wait"
    default: "1000"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
